
export const NEW_TOOL = 'NEW_TOOL'
export const NEW_TOOL_SUCCESS = 'NEW_TOOL_SUCCESS'

export const CREATE_TOOL = 'CREATE_TOOL'
export const CREATE_TOOL_PENDING = 'CREATE_TOOL_PENDING'
export const CREATE_TOOL_SUCCESS = 'CREATE_TOOL_SUCCESS'
export const CREATE_TOOL_FAILURE = 'CREATE_TOOL_FAILURE'

export const LIST_TOOL = 'LIST_TOOL'
export const LIST_TOOL_PENDING = 'LIST_TOOL_PENDING'
export const LIST_TOOL_SUCCESS = 'LIST_TOOL_SUCCESS'
export const LIST_TOOL_FAILURE = 'LIST_TOOL_FAILURE'

export const DELETE_TOOL = 'DELETE_TOOL'
export const DELETE_TOOL_PENDING = 'DELETE_TOOL_PENDING'
export const DELETE_TOOL_SUCCESS = 'DELETE_TOOL_SUCCESS'
export const DELETE_TOOL_FAILURE = 'DELETE_TOOL_FAILURE'
